### ISSUE TITLE
Getting indexing progress stats

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#139]
We have progress stats for migration, and that's good, I today put that in Manyverse as a UI.

We would also need indexing stats for JITDB indexes and DB2 indexes. I've been thinking how to do that in a way that's not a naive polling of `getStatus()` every 500ms.

I'm thinking that we need some kind of Obv in JITDB and in DB2. In JITDB, the Obv could be emit `index.offset` for all indexes, updated in a throttled manner, like we do with migration stats every 1000th msg. In DB2, similarly.

What do you think @arj03 ?

**Comment by arj03** [comment]
Yeah I guess we can do something like that. We just need to be careful it will not slow down indexing significantly. But I guess we have okay benchmarks for that. I don't find the polling solution that bad because it normally is on a specific screen. But at least getting a overview of the jitdb indexes would be pretty cool to see.

**Comment by staltz** [comment]
In our case in Manyverse, the polling would be all the time since the indexing indicator is on the main screen. Unless there's a way of doing polling only when the db is indexing. Do we have some kind of boolean Obv for `isIndexing`?

**Comment by arj03** [comment]
I see. We don't have a general isIndexing. I look forward to seeing what you come up with :)
