### ISSUE TITLE
List of modules to update for ssb-db2 v2.0.0

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#223]
To use `where()`

- [x] ssb-blobs-purge **(2.0.0)**
- [x] ssb-conn **(3.0.0)**
- [x] ssb-ebt **(6.0.0)**
- [x] ssb-threads **(8.0.0)**
- [x] ~~ssb-suggest-lite~~ not needed
- [x] ~~ssb-friends~~ not needed
- [x] ~~ssb-social-index & ssb-about~~ whoever wants it can do it

cc @arj03

**Comment by arj03** [comment]
@staltz excellent idea with a list. I'm thinking we might not need to update ssb-social-index and ssb-about as I don't think any of use uses them? And so that way we don't give off the wrong impression. I would rather that if something starts using them with db2 that they then upgrades to db2 with where().

In browser-core I use ssb-conn & ssb-threads. Not ssb-blobs-purge & ssb-suggest-lite (yet). ssb-friends needs to be updated as well. I can take that one. Keen to try out the performance improvement so I have to upgrade to do that :-)

So we can add browser-core and browser-demo to that list.

**Comment by arj03** [comment]
It doesn't seem like ssb-conn uses db2 does it?

**Comment by staltz** [comment]
It does, in the conn-scheduler

**Comment by arj03** [comment]
Sweet!
