### ISSUE TITLE
Migrate between ssb-db and ssb-db2

### ISSUE THREAD

**Issue by arj03** [ssb-ngi-pointer/ssb-db2#4]
Add methods for migrating data from old flume
 - Code for this in jitdb repo

**Comment by staltz** [comment]
- [x] Basic migration script
- [x] Support `live: true`
- [ ] Reuse the same async-flumelog instance instead of recreating it
- [ ] If new log already exists, don't log scan with `old: true`
- [ ] If new log already exists, log scan with `live: true`
- [ ] If old log still exists, refuse to allow db2.add and db2.publish

**Comment by arj03** [comment]
Close as per #18
